
services:
  nginx:
    container_name: free_vpn_bot_nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - free_vpn_bot
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
      LOCATION: ${SERVER_URL}
      # Пути внутри контейнера, на которые монтируются боевые сертификаты
      CERT_FULLCHAIN_PATH: "/etc/nginx/certs/fullchain.pem"
      CERT_KEY_PATH:     "/etc/nginx/certs/privkey.pem"
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./certbot/data:/var/www/certbot

  marzban:
    image: gozargah/marzban:latest
    container_name: free_vpn_bot_marzban
    restart: always
    env_file: .env.marzban
    environment:
      UVICORN_HOST:       "0.0.0.0"
      UVICORN_PORT:       "8002"
      YOUR_DOMAIN:        ${DOMAIN}
      UVICORN_SSL_CERTFILE: "/etc/marzban/certs/fullchain.pem"
      UVICORN_SSL_KEYFILE:  "/etc/marzban/certs/privkey.pem"
      UVICORN_SSL_CA_TYPE:  "public"
    ports:
      - "1081:1081"
      - "127.0.0.1:8002:8002"
    networks:
      - free_vpn_bot
    volumes:
      
      - ./volumes/marzban:/var/lib/marzban

      - ./certbot/data:/var/www/certbot
      - /etc/timezone:/etc/timezone:ro
      - ./certs:/etc/marzban/certs:ro
      
    logging:
      driver: "json-file"
      options:
        max-size: "900k"
        max-file: "10"



  vpn_bot:
    image: free_vpn_bot
    container_name: free_vpn_bot
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - free_vpn_bot
    depends_on:
      - marzban

  instruction:
    build:
      context: .
    container_name: free_vpn_instruction
    command: python -m web.server
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
    - "0.0.0.0:9000:8080"
    networks:
      - free_vpn_bot
    depends_on:
      - marzban

networks:
  free_vpn_bot:
    driver: bridge

volumes:
  marz-storage:
    driver: local
