"""add email column to vpnusers

Revision ID: 155ab60f90d3
Revises: 36159a9e6985
Create Date: 2025-06-06 20:48:54.813301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155ab60f90d3'
down_revision = '36159a9e6985'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpnusers', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpnusers', 'email')
    # ### end Alembic commands ###
